pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                docker.withRegistry('https://sashok.jfrog.io/default-docker-virtual/', 'jfrog')
            }
        }
    }
}

   // docker.withRegistry('https://sashok.jfrog.io/default-docker-virtual/', 'jfrog') {

  //  def customImage = docker.build("my-image:${env.BUILD_ID}", "-f Dockerfile ./application")
