



node ('jenkins-docker'){
    checkout scm
     stage('Initialize'){
//        def dockerHome = tool 'myDocker'
//        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }
    stage('Building image'){
       container('docker') {
       def dockerfile = 'Dockerfile'
       def customImage = docker.build("my-image:${env.BUILD_ID}", "-f ${dockerfile} ./") 
       }
//    def dockerfile = 'Dockerfile'
//    def customImage = docker.build("my-image:${env.BUILD_ID}", "-f ${dockerfile} ./") 
    }
}
   // docker.withRegistry('https://sashok.jfrog.io/default-docker-virtual/', 'jfrog') {

  //  def customImage = docker.build("my-image:${env.BUILD_ID}", "-f Dockerfile ./application")
