apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzYXNob2suamZyb2cuaW8iOnsidXNlcm5hbWUiOiJ2YWxreXJoaWtsZXNvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IkwjUXVAR1kyZ3FEUnRwZCIsImVtYWlsIjoidmFsa3lyaGlrbGVzb25AZ21haWwuY29tIiwiYXV0aCI6ImRtRnNhM2x5YUdscmJHVnpiMjVBWjIxaGFXd3VZMjl0T2t3alVYVkFSMWt5WjNGRVVuUndaQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: sashoksecret
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sashokpy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sashokpy
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sashokpy
    spec:
      containers:
      - name: sashokpy
        image: sashok.jfrog.io/default-docker-virtual/sashokpy:buildversion
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: sashoksecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sashokpy
  name: sashok-service
  namespace: default
spec:
  clusterIP:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sashokpy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
