apiVersion: apps/v1
kind: Deployment
metadata:
  name: sashokpy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sashokpy
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sashokpy
    spec:
      containers:
      - name: sashokpy
        image: sashok.jfrog.io/default-docker-virtual/sashokpy:22
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
