apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc 
  namespace: jenkins
  labels:
    app: jenkins
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: default # managed-premium 
  resources:
    requests:
      storage: 5Gi # Change Me
